language: python
# ===== Linux =====
dist: xenial
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - "3.6-dev"
  - "3.7-dev"
  - "3.8-dev"
  - "3.9-dev"
matrix:
  fast_finish: true
  allow_failures:
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "3.8-dev"
    - python: "3.9-dev"
  include:
    # ======= OSX ========
    - name: "Python 3.7.3 on macOS 10.14"
      os: osx
      osx_image: xcode10.2  # Python 3.7.3 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
        - pip3 install codecov
      script: python3 -m pytest
      after_success: python 3 -m codecov
    #  ====== WINDOWS =========
    - name: "Python 3.5.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.5.4
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install codecov
      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
    - name: "Python 3.6.8 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.6.8
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install codecov
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: "Python 3.7.8 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.8
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install codecov
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - name: "Python 3.8.5 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.5
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install codecov
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
# env:
#   - TO_RUN=TESTS
#   - TO_RUN=BUILD
# notifications:
#   email:
#     on_success: change
#     on_failure: always
before_install:
  # - pip install cython
  # - pip install numpy pandas scipy
  # - git clone https://github.com/facebookresearch/fastText.git
  # - cd fastText
  # - pip install .
  # - cd ..
  # - pip install scikit-learn
  - pip3 install --upgrade pip
  - pip3 install --upgrade pytest
  # - pip install git+https://github.com/facebookresearch/fastText.git@ca8c5face7d5f3a64fff0e4dfaf58d60a691cb7c
  # - pip3 install git+git://github.com/facebookresearch/fastText.git@0a5759475265705b485fa9fae4d1186d248049aa
  - pip3 install codecov
install:
  - pip3 install ".[test]"
script:
  - pytest
  - codecov
# after_success:
  # - codecov
